# This is the network config written by 'subiquity'
network:
  ethernets:
    eno1:
      dhcp4: true
    eno2:
      dhcp4: true
    enp1s0f0:
      dhcp4: true
    enp1s0f1:
      dhcp4: true
    enp1s0f2:
      dhcp4: false
      addresses: [192.168.40.3/24]
      gateway4: 192.168.40.1
    enp1s0f3:
      dhcp4: true
  version: 2
