version: "3.0"
services:
  mewa-db:
    image: mariadb:10.6.0
    logging:
      options:
        max-size: 1m
    restart: always
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: F71mGr
    container_name: mewa-db
    volumes:
      - /u01/app/mysql:/var/lib/mysql
  mewa-be:
    image: mewa-be:0.0.1
    restart: always
    network_mode: host
    privileged: true
    container_name: mewa-be
    logging:
      options:
        max-size: 1m
    depends_on:
      - mewa-db
    volumes:
      - /usr/lib/npreal2:/usr/lib/npreal2
      - /dev:/dev
      - /u01/app:/u01/app
    environment:
      SPRING_APPLICATION_JSON: '{
            "siu.ip": "192.168.40.40",
            "siu.port": "10014",
            "spring.datasource.password": "F71mGr"
        }'
