server:
  port: 8085
  incoming-port: 8000
  servlet:
    context-path: /mewa
moxa:
  init:
    configuration:
      - id: 1
        ip: 192.168.40.120
      - id: 2
        ip: 192.168.40.121
      - id: 3
        ip: 192.168.40.122
  config-file-path: /usr/lib/npreal2/driver/npreal2d.cf
siu:
  ip: 192.168.1.1
  port: 10014
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mewa
    username: root
    password: F71mGr
    driver-class-name: org.mariadb.jdbc.Driver
cron:
  request-frequency: '*/1 * * * * *'
oxygen:
  url: http://192.168.40.10/json
