server:
  port: 8085
  servlet:
    context-path: /mewa
moxa:
  ip: 192.168.40.120
  port: 80
  script-path: /home/ksedek/test/test.sh
  config-file-path: npreal2d.cf
  devices:
      - moxa-id: 1
        device-type: PRESS
        threshold-pressure: 1000
siu:
  ip: 192.168.24.243
  port: 80
